# ── Set wallpaper ──
# Start the awww daemon in the background
exec-once = awww-daemon
# Set your initial wallpaper (using the clear/no-transition flag for a faster boot)
exec-once = sleep 0.5 && awww img $HOME/wallpapers/wallpaper.jpg --transition-type none

# Run the background script to dynamically change the wallpaper based on active view and other parameters
exec-once = ~/scripts/dynamic-wallpaper-changer.sh

exec-once = kdeconnect-indicator

# --- Start Quickshell ---
exec-once = quickshell

# --- Enable screensharing for wayland ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

# --- Lock screen / sleep when idle ---
exec-once = swayidle -w timeout 600 'swaylock -f --image ~/wallpapers/wallpaper.jpg' timeout 1200 'systemctl suspend' before-sleep 'swaylock -f --image ~/wallpapers/wallpaper.jpg'
